// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2aRPWUbNWn8WpmgnyY45wpJL5d-CTUbk',
    appId: '1:596749462611:web:949acf171e3514b6742aa6',
    messagingSenderId: '596749462611',
    projectId: 'symme-a0f87',
    authDomain: 'symme-a0f87.firebaseapp.com',
    databaseURL: 'https://symme-a0f87-default-rtdb.firebaseio.com',
    storageBucket: 'symme-a0f87.firebasestorage.app',
    measurementId: 'G-M0SZ0CEHWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8FkE_Z_GdZ8HBXEP7JNDw3uszrgmcN38',
    appId: '1:596749462611:android:4656e62a8a89d460742aa6',
    messagingSenderId: '596749462611',
    projectId: 'symme-a0f87',
    databaseURL: 'https://symme-a0f87-default-rtdb.firebaseio.com',
    storageBucket: 'symme-a0f87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBzL6fixAqWcdoVvqBcFgIUwIPh5UprUU',
    appId: '1:596749462611:ios:f80fd774afb73049742aa6',
    messagingSenderId: '596749462611',
    projectId: 'symme-a0f87',
    databaseURL: 'https://symme-a0f87-default-rtdb.firebaseio.com',
    storageBucket: 'symme-a0f87.firebasestorage.app',
    iosBundleId: 'com.gatiella.symmeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBzL6fixAqWcdoVvqBcFgIUwIPh5UprUU',
    appId: '1:596749462611:ios:f80fd774afb73049742aa6',
    messagingSenderId: '596749462611',
    projectId: 'symme-a0f87',
    databaseURL: 'https://symme-a0f87-default-rtdb.firebaseio.com',
    storageBucket: 'symme-a0f87.firebasestorage.app',
    iosBundleId: 'com.gatiella.symmeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2aRPWUbNWn8WpmgnyY45wpJL5d-CTUbk',
    appId: '1:596749462611:web:0e96f79293431f30742aa6',
    messagingSenderId: '596749462611',
    projectId: 'symme-a0f87',
    authDomain: 'symme-a0f87.firebaseapp.com',
    databaseURL: 'https://symme-a0f87-default-rtdb.firebaseio.com',
    storageBucket: 'symme-a0f87.firebasestorage.app',
    measurementId: 'G-YL0WJHPV5R',
  );

}